name: Docker Build and Publish

on:
  release:
    types: [published] # Se ejecuta al publicar un release
  workflow_dispatch: # Permite ejecutar manualmente desde GitHub Actions

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      # Clona el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configura Docker para trabajar con GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Construye y etiqueta la imagen
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/quizz-cloud-front:${{ github.ref_name }} .

      # Publica la imagen en GHCR
      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository }}/quizz-cloud-front:${{ github.ref_name }}
